Repository MyBitFoundation/MyBit.io, pull requests merged in 2018-05, with the labels that each got.

#20 Grouped diamond highlights
  components/constants/index.js
  components/highlights.js
  components/highlights.scss
  stories/v2.stories.js
Labels: review-last

#29 Added secondary pages
  components/achievements.js
  components/background-video.js
  components/bit.js
  components/button.js
  components/card.js
  components/footer.js
  components/header.js
  components/hero.js
  components/highlights.js
  components/icon.js
  components/industries.js
  components/media-cta.js
  components/media.js
  components/nav.js
  components/news.js
  components/paragraph.js
  components/partners.js
  components/roadmap.js
  components/section.js
  components/team-members.js
  components/team.js
  components/video-player.js
  components/wallets.js
  next.config.js
  package.json
  pages/about-us.js
  pages/access-layer.js
  pages/asset-manager.js
  pages/community.js
  pages/investor.js
  pages/products.js
  stories/v2.stories.js
Labels: ready-for-review

#17 Feature/header
  components/background-video.scss
  components/footer.js
  components/header.js
  components/header.scss
  components/hero-banner.js
  components/hero-banner.scss
  components/link.js
  components/link.scss
  components/main-title.scss
  components/menu.js
  components/menu.scss
  components/paragraph.js
  components/paragraph.scss
  components/video-player.scss
  package-lock.json
  package.json
  pages/index.js
  static/assets/top_left_gradient.png
  static/svgs/icons/hamburger.svg
  static/svgs/icons/mybit.svg
  stories/v2.stories.js
Labels: work-in-progress

#37 About us page
  components/constants/index.js
  components/team-members.scss
  pages/about-us.js
  static/svgs/icons/menu-icon.svg
Labels: ready-for-review

#43 Feature/product page
  components/header.scss
  pages/about-us.js
  pages/products.js
Labels: ready-for-review

#53 feature/swap-popup
  components/swap-popup.js
  components/swap-popup.scss
  pages/about-us.js
  pages/index.js
Labels: ready-for-review
